/* COPYRIGHT (C) HARRY CLARK 2023 */

/* SONIC THE HEDGEHOG UNITY PROJECT */

/* THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY SURROUDNING THE STATE MACHINE */
/* PROVIDING FUNCTIONALITY INTO THE VARIOUS STATES THAT SONIC WILL BE IN */
/* THROUGH ANIMATIONS AND PHYSICS */

using UnityEngine;

public class SONIC_STATE : SONIC_MAIN
{
    public struct STATE_TYPES
    {
        private static void SET_STATE_TYPE<T>(){}
        private static void SET_STATE_ENUM(int INDEX){}
    }
}
